import test from 'node:test';import assert from 'node:assert/strict';
import {ageFieldErrors} from '../src/age-validation.js';import {validateBackground} from '../server/core.js';import {timeAnchors,hardConflicts} from '../src/input-anchors.js';
import {finishReview,completeReview,closeConversation,reviseMemories} from '../src/memory-review.js';import {readLives,writeLives} from '../src/life-store.js';import {demoStory} from '../src/services/demo.js';
const life=()=>({id:'offline49',story:demoStory,background:{},messages:[],memories:[],candidates:[]});let serial=0;
const round=(l,text)=>completeReview(finishReview(closeConversation({...l,messages:[...l.messages,{id:'u'+(++serial),role:'user',status:'sent',text}]})));
const texts=l=>l.memories.map(m=>m.text).join('|');
const restore=l=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};assert.equal(writeLives(storage,{activeId:l.id,lives:[l]}),true);return readLives(storage).lives[0];};
test('required integers, birthday bounds, future event age, estimated year',()=>{for(const x of ['', '不确定','不愿透露','23.5','-1'])assert.ok(ageFieldErrors({birthYear:'2000',forkAge:x}).forkAge);for(const x of ['', '200','2000.0'])assert.ok(ageFieldErrors({birthYear:x,forkAge:'23'}).birthYear);for(const age of ['26','27']){const b={birthYear:'2000',forkAge:age,realityOutcome:'现在2026年9月还没有申请',hypotheticalDirection:'2027年4月驻留半年'};assert.deepEqual(ageFieldErrors(b),{});assert.equal(hardConflicts(b).filter(c=>c.field==='time').length,0);}assert.ok(ageFieldErrors({birthYear:'2000',forkAge:'25',hypotheticalDirection:'2027年4月驻留半年'}).forkAge);assert.deepEqual(timeAnchors({birthYear:'2000',forkAge:'23'}).start,{year:2023,month:null,estimated:true});});
test('new server submission rejects unknown, historical restore remains valid',()=>{const b={inputVersion:'6',realityOutcome:'过去没出发',hypotheticalDirection:'这次出发',details:''};assert.throws(()=>validateBackground(b,{newSubmission:true}));assert.doesNotThrow(()=>validateBackground(b));assert.doesNotThrow(()=>validateBackground({...b,birthYear:'2000',forkAge:'23'},{newSubmission:true}));});
test('cross-session learning correction and addition survive restore',()=>{let l=restore(round(life(),'我最近在学贝斯'));assert.match(texts(l),/贝斯/);l=restore(round(l,'说错了，是吉他'));assert.match(texts(l),/吉他/);assert.doesNotMatch(texts(l),/贝斯/);l=restore(round(l,'后来两种都学'));assert.match(texts(l),/吉他/);assert.match(texts(l),/贝斯/);assert.ok(l.memories.every(m=>m.sourceRole==='user'&&m.sourceId));});
test('compound language and weekly habit; correction changes object only',()=>{let l=round(life(),'学西班牙语＋每周游泳');assert.match(texts(l),/西班牙语/);assert.match(texts(l),/游泳/);l=round(l,'说错了，是意大利语');assert.match(texts(l),/意大利语/);assert.match(texts(l),/游泳/);assert.doesNotMatch(texts(l),/西班牙语/);});
test('explicit negative attribute invalidates previous preference',()=>{let l=round(life(),'喜欢甜咖啡');l=round(l,'现在不喜欢甜的');assert.doesNotMatch(texts(l),/兴趣偏好：甜咖啡/);assert.match(texts(l),/不喜欢：甜的/);});
test('questions, third party, role and future plan remain separate',()=>{let l=life();for(const text of ['你最近在学贝斯吗','我朋友最近在学贝斯'])l=round(l,text);assert.equal(l.memories.length,0);l.messages.push({id:'a',role:'assistant',text:'我在学贝斯'});l=completeReview(finishReview(l));assert.equal(l.memories.length,0);l=round(l,'我打算学贝斯');assert.ok(l.memories.every(m=>m.type==='preference'));});
test('deletion suppression and another story isolation',()=>{let a=round(life(),'我最近在学贝斯');const b=round({...life(),id:'B'},'你好');assert.equal(b.memories.length,0);a=reviseMemories(a,[]);a.sessionMeta.organizedUntil=0;a.sessionMeta.review=null;a=completeReview(finishReview(a));assert.equal(a.memories.length,0);});
test('pending messages are not marked processed, later sent version extracted',()=>{let l=life();l.messages=[{id:'pending',role:'user',status:'pending',text:'我最近在学贝斯'}];l=finishReview(l);assert.equal(l.sessionMeta.organizedUntil,0);l.messages[0].status='sent';l=completeReview(finishReview(l));assert.match(texts(l),/贝斯/);});

import {persistLifeChange} from '../src/life-store.js';
test('failed durable write leaves processing cursor unchanged; retry processes same messages',()=>{const l={...life(),messages:[{id:'x',role:'user',status:'sent',text:'我最近在学贝斯'}]},transform=l=>completeReview(finishReview(l));const broken={getItem:()=>null,setItem:()=>{throw Error('quota');}};const failed=persistLifeChange(broken,[l],l.id,l.id,l,transform);assert.equal(failed.okay,false);assert.equal(failed.next,l);assert.equal(failed.next.sessionMeta?.organizedUntil,undefined);const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};const okay=persistLifeChange(storage,[l],l.id,l.id,failed.next,transform);assert.equal(okay.okay,true);assert.match(texts(readLives(storage).lives[0]),/贝斯/);assert.equal(okay.next.sessionMeta.organizedUntil,1);});

test('two learning objects are separate; explicit correction does not replace whole category',()=>{let l=round(life(),'我在学西班牙语，我在学吉他，每周游泳');assert.equal(l.memories.length,3);l=round(l,'说错了，是意大利语，不是西班牙语');assert.match(texts(l),/意大利语/);assert.match(texts(l),/吉他/);assert.match(texts(l),/游泳/);assert.doesNotMatch(texts(l),/西班牙语/);});
