import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createMemoryTasks,normalizeMemoryResult} from '../server/memory-extraction.js';import {acceptMemoryResult,memoryInput} from '../src/model-memory.js';import {completeReview} from '../src/memory-review.js';import {AppError} from '../server/core.js';
const life=()=>({id:'a',memoryRevision:1,memories:[{id:'m',text:'旧事实',type:'reality'}],candidates:[],messages:[{id:'u',role:'user',text:'我正在学习新技能',status:'sent'}],sessionMeta:{organizedUntil:0}});
const op={subject:'user',timeState:'current',subjectEvidence:'我',sourceId:'u',kind:'add',targetId:null,type:'reality',text:'学习新技能',evidence:'我正在学习新技能',needsConfirmation:false};
for(const value of [false,true,undefined,null,'false','true',0,1,{},[]])test('confirmation '+JSON.stringify(value),()=>{const l=life(),input=memoryInput(l),job={id:'b',input,expectedRevision:1};l.sessionMeta.memoryJob=job;const result=normalizeMemoryResult({operations:[{...op,needsConfirmation:value}]},input,'b');const n=acceptMemoryResult(l,job,result);assert.equal(n.candidates.length,value===false?0:1);assert.equal(n.memories.length,value===false?2:1);if(value!==false){const done=completeReview(n,n.candidates.map(c=>c.id));assert.equal(done.memories.length,2);}});
for(const kind of ['update','revoke'])test('pending '+kind+' preserves operation and expected target',()=>{const l=life(),input=memoryInput(l),job={id:'b',input,expectedRevision:1};l.sessionMeta.memoryJob=job;const result=normalizeMemoryResult({operations:[{...op,kind,targetId:'m',needsConfirmation:null}]},input,'b');const n=acceptMemoryResult(l,job,result);assert.equal(n.memories[0].text,'旧事实');assert.throws(()=>completeReview({...n,memories:[{...n.memories[0],text:'手工编辑'}]},['b:0']),/stale/);const done=completeReview(n,['b:0']);assert.equal(done.memories.length,kind==='revoke'?0:1);});
test('retry is explicit bounded and aliases cannot bypass fingerprint or budget',async()=>{let calls=0;const tasks=createMemoryTasks({instanceId:'i',run:async(d,id)=>{calls++;if(calls===1)throw new AppError('invalid_response',502);return {lifeId:d.lifeId,batchId:id,operations:[]};}});const input={instanceId:'i',batchId:randomUUID(),data:memoryInput(life())};await assert.rejects(tasks.submit('a',input));await assert.rejects(tasks.submit('a',input));assert.equal(calls,1);const retry={...input,attempt:1};await Promise.all([tasks.submit('a',retry),tasks.submit('a',retry)]);assert.equal(calls,2);const alias={...retry,batchId:randomUUID()};assert.equal((await tasks.submit('a',alias)).batchId,alias.batchId);assert.equal(calls,2);assert.throws(()=>tasks.submit('a',{...alias,data:{...input.data,memories:[]}}),/task_input_changed/);assert.throws(()=>tasks.submit('a',{...retry,attempt:2}),/retry_exhausted/);assert.throws(()=>tasks.submit('b',retry),/task_missing/);assert.throws(()=>tasks.submit('a',{...retry,instanceId:'old'}),/task_expired/);});
test('unknown transport failure does not authorize another call',async()=>{let n=0;const t=createMemoryTasks({instanceId:'i',run:async()=>{n++;throw new AppError('timeout');}}),input={instanceId:'i',batchId:randomUUID(),data:memoryInput(life())};await assert.rejects(t.submit('a',input));assert.throws(()=>t.submit('a',{...input,attempt:1}),/retry_exhausted/);assert.equal(n,1);});

import {retryMemoryJob} from '../src/model-memory.js';
test('restart requires explicit rebuild and persisted retry budget',()=>{const old={id:'old',instanceId:'old-server',error:'task_expired'};const fresh=retryMemoryJob(old,'new-server','new-id');assert.equal(fresh.attempt,0);assert.equal(fresh.id,'new-id');assert.equal(fresh.retryUsed,1);assert.throws(()=>retryMemoryJob({...fresh,error:'invalid_response'},'third-server','another'),/exhausted/);});
test('saved user message with failed reply is a valid memory source',()=>{const l=life();l.messages[0].status='failed';const input=memoryInput(l),job={id:'b',input,expectedRevision:1};l.sessionMeta.memoryJob=job;const n=acceptMemoryResult(l,job,normalizeMemoryResult({operations:[op]},input,'b'));assert.equal(n.memories.length,2);});
