import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {applyMemoryOperations} from '../src/memory-operations.js';import {proposeMemories,finishReview,completeReview,closeConversation,reviseMemories,revisitMemories} from '../src/memory-review.js';import {persistLifeChange,readLives,writeLives} from '../src/life-store.js';
const base=()=>({id:'A',story:{scenes:[]},background:{},messages:[],memories:[],candidates:[]});
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
const message=(l,text)=>({...l,messages:[...l.messages,{id:'u'+l.messages.length,role:'user',text,status:'sent'}]});
const end=l=>completeReview(finishReview(closeConversation(l)));
const save=(s,l,transform=end)=>{const r=persistLifeChange(s,[l],l.id,l.id,l,transform);assert.equal(r.okay,true);return readLives(s).lives[0];};
test('mock operation batches: add/update/revoke, stable target ID, multi-fact, repeated result and source checks',()=>{let l=message(base(),'合成用户信息');const apply=operations=>l=applyMemoryOperations(l,{lifeId:'A',operations});const b={sourceId:'u0',type:'reality'};apply([{...b,id:'1',kind:'add',targetId:'m1',text:'事项甲'},{...b,id:'2',kind:'add',targetId:'m2',text:'事项乙'}]);const op={...b,id:'3',kind:'update',targetId:'m1',expectedText:'事项甲',text:'事项丙'};apply([op]);apply([op]);assert.deepEqual(l.memories.map(m=>m.text),['事项丙','事项乙']);apply([{...b,id:'4',kind:'revoke',targetId:'m2',expectedText:'事项乙'}]);assert.equal(l.memories[0].id,'m1');assert.throws(()=>applyMemoryOperations(l,{lifeId:'B',operations:[]}));assert.throws(()=>apply([{...b,id:'5',sourceId:'missing',kind:'add',targetId:'x',text:'伪造'}]));assert.throws(()=>apply([{...op,id:'6'}]),/stale/);});
test('fixed dialogue end -> operations -> storage -> reader, across rounds; trace saved locally',()=>{const s=storage(),trace=[];let l=base();for(const text of ['我最近在学贝斯','说错了，是吉他','现在两种都学']){l=message(l,text);const extraction=proposeMemories(l);trace.push({range:extraction.stats,candidates:extraction.candidates,operations:extraction.candidates.flatMap(c=>c.operations||[])});l=save(s,l);trace.at(-1).stored=l.memories;trace.at(-1).cursor=l.sessionMeta.organizedUntil;}assert.deepEqual(l.memories.map(m=>m.text).sort(),['正在学习：吉他。','正在学习：贝斯。']);const count=l.messages.length;l=save(s,l);assert.equal(l.messages.length,count);assert.equal(l.memories.length,2);fs.writeFileSync('.local/memory50-replay.json',JSON.stringify(trace,null,2));});
test('saved manual composite card is partially corrected, edited stale candidate fails instead of silent add',()=>{const s=storage();let l=save(s,message(base(),'学西班牙语＋每周游泳'));l=save(s,message(l,'说错了，是意大利语'));assert.match(JSON.stringify(l.memories),/游泳/);assert.doesNotMatch(JSON.stringify(l.memories.map(m=>m.text)),/西班牙语/);l=message(l,'说错了，是法语');const pending=finishReview(l);pending.memories=pending.memories.map(m=>m.text.includes('意大利语')?{...m,text:'用户手动改过'}:m);assert.throws(()=>completeReview(pending),/stale/);});
test('ambiguous correction is retained for explicit replacement, never silently added',()=>{const s=storage();let l=save(s,message(base(),'我在学西班牙语，我在学吉他'));l=save(s,message(l,'说错了，是意大利语'));assert.equal(l.memories.length,2);assert.equal(l.candidates.length,1);assert.equal(l.sessionMeta.memoryOutcome,'confirmation');const target=l.memories.find(m=>m.text.includes('西班牙语'));l.candidates=l.candidates.map(c=>({...c,confirmTargetId:target.id,text:'正在学习：意大利语。',operations:undefined}));l=save(s,l,x=>completeReview(x,x.candidates.map(c=>c.id)));assert.equal(l.memories.length,2);assert.equal(l.memories.find(m=>m.id===target.id).text,'正在学习：意大利语。');});
test('write failure, fresh source after deletion, isolation while A retains memory, stale result protection',()=>{const s=storage();let l=save(s,message(base(),'我最近在学贝斯'));const old=l;l=save(s,message(l,'说错了，是吉他'));assert.equal(persistLifeChange(s,[old],'A','A',old,end).okay,false);assert.equal(writeLives(s,{lives:[old]}),false);const failed=persistLifeChange({getItem:()=>null,setItem:()=>{throw Error('quota');}},[l],'A','A',message(l,'每周游泳'),end);assert.equal(failed.okay,false);assert.equal(failed.next.sessionMeta.organizedUntil,l.sessionMeta.organizedUntil);const b=save(storage(),message({...base(),id:'B'},'你好'));assert.equal(b.memories.length,0);assert.ok(l.memories.length);l=save(s,l,x=>reviseMemories(x,[]));l=save(s,l,x=>completeReview(revisitMemories(x)));assert.equal(l.memories.length,0);l=save(s,message(l,'我最近在学吉他'));assert.equal(l.memories.length,1);});

test('browser acceptance exact wording across three saved rounds',()=>{const s=storage();let l=base();l=save(s,message(l,'最近学贝斯'));assert.deepEqual(l.memories.map(m=>m.text),['正在学习：贝斯。']);l=save(s,message(l,'说错了，学的是吉他'));assert.deepEqual(l.memories.map(m=>m.text),['正在学习：吉他。']);l=save(s,message(l,'现在两种都学'));assert.deepEqual(l.memories.map(m=>m.text).sort(),['正在学习：吉他。','正在学习：贝斯。']);});
