import test from 'node:test';import assert from 'node:assert/strict';
import {QUESTION_BANK,QUESTION_BY_ID} from '../src/question-bank.js';
import {saveSupplement,supplementState,supplementaryContext,validateSupplement,finishSupplementPage} from '../src/supplementary.js';
import {normalizePlan,plannerMessages,createPlannerTasks} from '../server/supplementary-planner.js';
import {migrateBackground} from '../src/background.js';import {writeDraft,readDraft} from '../src/draft.js';
import {storyMessages} from '../server/prompts.js';import {timeAnchors} from '../src/input-anchors.js';
const base=()=>migrateBackground({birthYear:'2000',forkAge:'27',gender:'不透露',mbti:'unknown',locationText:'南京',realityOutcome:'尚未申请，也没参加过陶艺课。',hypotheticalDirection:'假设2027年5月报名成功，只看之后两个月。',choiceReason:'',lifeSituation:'',details:''});
const raw=ids=>({questions:ids.map(id=>({id,reason:'这项未知会影响具体行动',tense:'future',informationGain:2,missingInformation:'具体行为尚未知',useInStory:'影响角色行动'})),covered:[],conflict:null,expectations:{mustKeep:[],respondTo:[],free:[],unknown:[]}});
test('revised 35-item bank excludes base/result questions and merges equivalent dimensions',()=>{assert.equal(QUESTION_BANK.length,35);for(const id of ['G01','G02','G03','G13','F02'])assert.equal(QUESTION_BY_ID[id],undefined);for(const id of ['G04','G07','S02'])assert.equal(QUESTION_BY_ID[id].kind,'text');assert.equal(QUESTION_BY_ID.G04.group,QUESTION_BY_ID.S02.group);assert.equal(normalizePlan(raw(['G04','S02','G14']),base()).questions.length,1);});
test('source-backed manual answer removes newly covered dimensions; ungrounded model claim cannot',()=>{let b=base(),s=supplementState(b);s.shown=['I01'];s.answers.I01={selected:[],text:'没学过。会先问懂的人，只想周末玩，不打算当工作。',skipped:false};b=saveSupplement(b,s);const r=raw(['G11','I02','G08']);r.covered=[{id:'G11',sourceId:'I01',evidence:'会先问懂的人'},{id:'I02',sourceId:'I01',evidence:'只想周末玩'}];assert.deepEqual(normalizePlan(r,b).questions.map(x=>x.id),['G08']);r.covered[0].evidence='并不存在';assert.ok(normalizePlan(r,b).questions.some(x=>x.id==='G11'));assert.ok(plannerMessages(b)[1].content.includes(s.answers.I01.text));});
test('shown, skipped, equivalent dimensions and eight-question budget block repeat selection',()=>{let b=base(),s=supplementState(b);s.shown=['G04','G05','G07','G08','G09','G10','G12'];s.answers.G04={selected:[],text:'',skipped:true};b=saveSupplement(b,s);assert.deepEqual(normalizePlan(raw(['S02','W02','R05']),b).questions,[]);assert.equal(normalizePlan(raw(['S01','S04','W04']),b).questions.length,1);s.shown.push('S01');assert.equal(normalizePlan(raw(['S04']),saveSupplement(base(),s)).questions.length,0);});
test('return/edit/refresh retains raw choices and text; changed core input invalidates but preserves recoverable old context',()=>{const b=base(),s=supplementState(b);s.shown=['G08'];s.pages=[['G08']];s.answers.G08={selected:['做决定前列清单'],text:'会先比较几种方法。',skipped:false};const filled=saveSupplement(b,s),map=new Map(),disk={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};assert.equal(writeDraft(disk,{background:filled}),true);const read=readDraft(disk).background;assert.equal(supplementState(read).answers.G08.text,s.answers.G08.text);const changed={...read,hypotheticalDirection:'假设去另一座城市'};assert.equal(supplementState(changed).answers.G08,undefined);assert.equal(supplementState(changed).plan,null);const saved=saveSupplement(changed,supplementState(changed));assert.equal(supplementState({...saved,hypotheticalDirection:b.hypotheticalDirection}).answers.G08.text,s.answers.G08.text);});
test('raw future and third-party statements enter generation with purpose and scope, without rewriting base facts',()=>{let b=base(),s=supplementState(b);s.shown=['G04'];s.answers.G04={selected:[],text:'希望和朋友一起练，但朋友是否参加还不知道。',skipped:false};b=saveSupplement(b,s);const data=JSON.parse(storyMessages(b)[1].content);assert.equal(b.realityOutcome,base().realityOutcome);assert.equal(data.effectiveSetting.personalization.answers[0].text,s.answers.G04.text);assert.ok(data.effectiveSetting.personalization.answers[0].purpose.includes('不保证'));assert.equal(supplementaryContext(b).answers.length,1);assert.equal(timeAnchors(b).start.year,2027);});
test('range answer is compiled and unknown month stays unknown',()=>{let b=base(),s=supplementState(b);s.shown=['G14'];s.answers.G14={selected:['接下来一年'],text:'',skipped:false};b={...b,hypotheticalDirection:'假设报名成功。'};b=saveSupplement(b,s);assert.equal(timeAnchors(b).window.months,12);s.answers.G14.selected=['刚开始的几周'];b=saveSupplement(b,s);assert.equal(timeAnchors(b).window.start.month,null);assert.equal(timeAnchors(b).window.weeks,3);});
test('conflict is separate and must cite real opposing source fragments',()=>{const b={...base(),hypotheticalDirection:'假设报名成功。假设没有报名成功。'},r=raw(['G04']);r.conflict={question:'请明确这次希望成立的设定',evidence:[{sourceId:'hypotheticalDirection',text:'假设报名成功'},{sourceId:'hypotheticalDirection',text:'假设没有报名成功'}]};const result=normalizePlan(r,b);assert.equal(result.questions.length,0);assert.ok(result.conflict);r.conflict.evidence[0].text='假的引文';assert.throws(()=>normalizePlan(r,b));});
test('owner-scoped repeated plan uses one mocked call; edits trigger another, invalid answers rejected',async()=>{let calls=0;const run=createPlannerTasks(async()=>{calls++;return raw([]);});await run('a',base());await run('a',base());assert.equal(calls,1);await run('b',base());await run('a',{...base(),choiceReason:'改了'});assert.equal(calls,3);const s=supplementState(base());s.shown=['G04'];s.answers.G04={selected:['造出的选项'],text:'',skipped:false};assert.throws(()=>validateSupplement(saveSupplement(base(),s)));});

test('skips remain unknown in generation and existing constraints suppress the merged boundary question',()=>{let b={...base(),details:'朋友不参加；希望每周留出一个晚上。'},s=supplementState(b);s.shown=['G09'];s.answers.G09={selected:[],text:'',skipped:true};b=saveSupplement(b,s);assert.deepEqual(supplementaryContext(b).skipped,['G09']);assert.equal(supplementaryContext(b).answers.length,0);assert.deepEqual(normalizePlan(raw(['G07','M04','R05']),b).questions,[]);});
test('UI page changes and model metadata cannot create another identical paid planning call',async()=>{let calls=0;const run=createPlannerTasks(async()=>{calls++;return raw([]);});let b=base(),s=supplementState(b);s.shown=['G04'];s.pages=[['G04']];b=saveSupplement(b,s);await run('owner',b);s={...s,page:1,plan:normalizePlan(raw([]),b)};await run('owner',saveSupplement(b,s));assert.equal(calls,1);s.answers.G04={selected:[],text:'想试着做一个能用的杯子。',skipped:false};await run('owner',saveSupplement(b,s));assert.equal(calls,2);});
test('malformed navigation state and third core-confirmation answer are rejected',()=>{const b=base(),s=supplementState(b);s.pages=[['missing']];assert.throws(()=>validateSupplement(saveSupplement(b,s)));s.pages=[];s.confirmations=['一','二','三'];assert.throws(()=>validateSupplement(saveSupplement(b,s)));});

test('unknown short answer finishes as skipped without losing original; substantive uncertainty remains',()=>{const s=supplementState(base());s.shown=['G04','G08'];s.answers={G04:{selected:[],text:'不知道。',skipped:false},G08:{selected:[],text:'不知道怎么说，但我喜欢记笔记。',skipped:false}};const done=finishSupplementPage(s,s.shown);assert.equal(done.answers.G04.skipped,true);assert.equal(done.answers.G04.text,'不知道。');assert.equal(done.answers.G08.skipped,false);assert.equal(supplementaryContext(saveSupplement(base(),done)).answers.length,1);});
test('plot-focus question is excluded from live selection, old answers remain readable',()=>{const b=base();assert.ok(!JSON.parse(plannerMessages(b)[1].content).bank.some(q=>q.id==='G12'));assert.deepEqual(normalizePlan(raw(['G12']),b).questions,[]);const s=supplementState(b);s.shown=['G12'];s.answers.G12={selected:[],text:'此前填写的关注点',skipped:false};assert.equal(supplementaryContext(saveSupplement(b,s)).answers[0].text,'此前填写的关注点');});

import {planWithGapCheck} from '../server/supplementary-planner.js';
test('initial zero questions gets one independent gap review without a quota',async()=>{
 const b={...base(),lifeSituation:'全职工作，晚上回家休息。'};let calls=0;
 const reviewed=ids=>({...raw(ids),questions:raw(ids).questions.map(q=>({...q,questionText:QUESTION_BY_ID[q.id].question})),keepScenario:false,changeSubject:'self',evidence:b.hypotheticalDirection});
 const caller={call:async(task,m,options)=>{calls++;const result=calls===1?raw([]):reviewed(['G16','G18']);if(calls===2)assert.ok(m[0].content.includes('独立的补充题逻辑审查器'));options.validateResult(result);return {result};}};
 const p=await planWithGapCheck(b,caller);assert.equal(calls,2);assert.deepEqual(p.questions.map(q=>q.id),['G16','G18']);
 calls=0;const none=await planWithGapCheck(b,{call:async()=>{calls++;return {result:calls===1?raw([]):reviewed([])};}});assert.equal(calls,2);assert.equal(none.questions.length,0);
 let s=supplementState(b);s.shown=['G16'];s.pages=[['G16']];s.answers.G16={selected:[],text:'不知道',skipped:true};calls=0;await planWithGapCheck(saveSupplement(b,s),{call:async()=>{calls++;return {result:raw([])};}});assert.equal(calls,1);
});

import {questionTime,questionTitle} from '../src/question-context.js';
import {questionReviewMessages,validateQuestionReview} from '../server/question-review.js';
test('past question time overrides incorrect model future marker and saved labels',()=>{const b={...base(),forkAge:'25',realityOutcome:'2025年9月朋友没有回复我的消息。',hypotheticalDirection:'如果2025年9月朋友主动回复我。'};assert.equal(questionTime(b).tense,'original');assert.equal(normalizePlan(raw(['G16']),b).questions[0].tense,'original');assert.ok(!questionTitle(QUESTION_BY_ID.G16,{tense:'future',questionText:'现在遇到这种事，你会先做什么？'},b).includes('现在'));assert.equal(questionTime(base()).tense,'future');});
test('logic review changes a self-initiation question into appropriate relationship context and preserves displayed wording for generation',async()=>{const b={...base(),forkAge:'25',realityOutcome:'2025年9月朋友没有回复我的消息。',hypotheticalDirection:'如果2025年9月朋友主动回复我。'};let calls=0;const app={call:async(task,m,opt)=>{calls++;const result=calls===1?raw(['R01']):{...raw(['R02']),questions:[{id:'R02',questionText:'那件事发生前，你们通常怎样相处？',reason:'了解原有相处，不要求用户先开口',informationGain:3,missingInformation:'原有相处方式',useInStory:'决定对话的熟悉程度'}],keepScenario:false,changeSubject:'other',evidence:'朋友主动回复我'};opt.validateResult(result);return {result};}};const plan=await planWithGapCheck(b,app);assert.equal(calls,2);assert.deepEqual(plan.questions.map(q=>q.id),['R02']);assert.equal(plan.changeSubject,'other');let s=supplementState(b);s.shown=['R02'];s.pages=[['R02']];s.questionMeta={R02:plan.questions[0]};s.answers.R02={selected:[],text:'以前经常聊天',skipped:false};assert.equal(supplementaryContext(saveSupplement(b,s)).answers[0].question,plan.questions[0].questionText);assert.ok(questionReviewMessages(b,plan)[0].content.includes('别人改变对用户的行为'));assert.throws(()=>validateQuestionReview({questions:[],covered:[],keepScenario:false,changeSubject:'other',evidence:'编造'},b));});
test('logic review failure never displays unchecked questions',async()=>{let n=0;const result=await planWithGapCheck(base(),{call:async()=>{if(++n===1)return {result:raw(['R01'])};throw Error('mock review failed');}});assert.equal(result.optionalAnalysisUnavailable,true);assert.deepEqual(result.questions,[]);assert.equal(n,2);});

import {questionSelectionState,validateQuestionAssessments} from '../server/question-policy.js';
test('information gain ranks six candidates, selects three distinct useful dimensions and does not fill a quota',()=>{const r=raw(['G08','G09','G16','G17','G18','G15']);r.questions.forEach((q,i)=>q.informationGain=[2,2,3,3,3,1][i]);assert.deepEqual(normalizePlan(r,base()).questions.map(q=>q.id),['G16','G17','G18']);r.questions.forEach(q=>q.informationGain=1);assert.deepEqual(normalizePlan(r,base()).questions,[]);assert.throws(()=>validateQuestionAssessments({questions:[{id:'G08'}]}));});
test('equivalent variants default to one dimension, including previously shown questions',()=>{for(const pair of [['G09','G16'],['G10','G17'],['I03','G18']]){assert.equal(normalizePlan(raw(pair),base()).questions.length,1);const s=supplementState(base());s.shown=[pair[0]];s.pages=[[pair[0]]];s.answers[pair[0]]={selected:[],text:'说不清',skipped:true};assert.equal(normalizePlan(raw([pair[1]]),saveSupplement(base(),s)).questions.length,0);}});
test('review shares context and cannot reopen a fully skipped group or exhausted budget',async()=>{const s=supplementState(base());s.shown=['G16'];s.pages=[['G16']];s.answers.G16={selected:[],text:'不知道',skipped:true};s.answerScopes={G16:{realityOutcome:'旧背景'}};s.confirmations=['假设成立'];const b=saveSupplement(base(),s),p=JSON.parse(questionReviewMessages(b,normalizePlan(raw([]),b))[1].content);assert.equal(p.selectionState.currentGroupSkipped,true);assert.deepEqual(p.answerContexts,s.answerScopes);assert.deepEqual(p.confirmations,s.confirmations);let calls=0;const plan=await planWithGapCheck(b,{call:async()=>{calls++;return {result:raw(['G08','G17','G18'])};}});assert.equal(calls,1);assert.equal(plan.questions.length,0);});
test('story prompt uses effective setting paths and keeps optional chat fields in chat only',()=>{const [sys,user]=storyMessages(base());for(const x of ['timeline.atFork','criticalFacts','confirmedMemories','styleHint.mbti'])assert.ok(!sys.content.includes(x),x);assert.ok(sys.content.includes('事件发生于当天，可以说'));assert.ok(!sys.content.includes('也不能再说今天才完成'));const p=JSON.parse(user.content);assert.ok(p.effectiveSetting.style);assert.ok(!('timeline' in p));});

test('two-stage ranking returns three useful questions and hard limits cannot reopen',async()=>{const score=ids=>({...raw(ids),questions:raw(ids).questions.map((q,i)=>({...q,questionText:QUESTION_BY_ID[q.id].question,informationGain:i===0?2:3})),keepScenario:false,changeSubject:'self',evidence:base().hypotheticalDirection});let calls=0;const result=await planWithGapCheck(base(),{call:async(task,m,opt)=>{calls++;const r=score(['G08','G16','G17','G18']);opt.validateResult(r);return {result:r};}});assert.equal(calls,2);assert.deepEqual(result.questions.map(q=>q.id),['G16','G17','G18']);const s=supplementState(base());s.shown=['G04','G05','G07','G08','G09','G10','G12','S01'];calls=0;const stopped=await planWithGapCheck(saveSupplement(base(),s),{call:async()=>{calls++;return {result:raw(['G18'])};}});assert.equal(calls,1);assert.equal(stopped.questions.length,0);assert.equal(questionSelectionState(saveSupplement(base(),s)).remaining,0);});

import {AppError} from '../server/core.js';
import {withoutOptionalAnalysis} from '../src/question-recovery.js';
test('invalid review retries only that stage once; repeated failure returns cached safe fallback',async()=>{let calls=0;const caller={call:async(task,m,o)=>{calls++;if(calls===1)return {result:raw(['G08'])};throw new AppError('invalid_response',502,{reason:'question_review_scenario_flag'});}};const run=createPlannerTasks(b=>planWithGapCheck(b,caller));const result=await run('owner',base());assert.equal(calls,3);assert.equal(result.optionalAnalysisUnavailable,true);assert.deepEqual(result.questions,[]);await run('owner',base());assert.equal(calls,3);});
test('one corrected review resumes questions, transport failure avoids blind paid resubmit',async()=>{let n=0;const r=await planWithGapCheck(base(),{call:async()=>{if(++n===1)return {result:raw(['G08'])};if(n===2)throw new AppError('invalid_response');return {result:{...raw(['G08']),questions:raw(['G08']).questions.map(q=>({...q,questionText:QUESTION_BY_ID[q.id].question})),keepScenario:false,changeSubject:'self',evidence:base().hypotheticalDirection}};}});assert.equal(n,3);assert.equal(r.questions.length,1);n=0;const fallback=await planWithGapCheck(base(),{call:async()=>{n++;throw new AppError('network');}});assert.equal(n,1);assert.equal(fallback.optionalAnalysisUnavailable,true);});
test('optional failure retains raw ordinary answers, removes unverified scenario analysis, preserves explicit conflicts',()=>{const s=supplementState(base());s.shown=['I03'];s.answers.I03={selected:[],text:'先自己试几次',skipped:false};s.scenario={id:'Q01',answer:'假设情景回答',analysis:{bad:true}};const next=withoutOptionalAnalysis(s);assert.deepEqual(next.answers,s.answers);assert.equal(next.scenario.answer,s.scenario.answer);assert.equal(next.scenario.analysis,null);s.plan={conflict:{question:'明确冲突'}};assert.deepEqual(withoutOptionalAnalysis(s).plan.conflict,s.plan.conflict);});
test('existing text can cover interest role and setback without keyword-equivalent option strings',()=>{const b={...base(),details:'我想固定留一点时间，碰到画不出来的地方会先自己试几次。'},r=raw(['I02','G10']);r.covered=[{id:'I02',sourceId:'details',evidence:'固定留一点时间'},{id:'G10',sourceId:'details',evidence:'画不出来的地方会先自己试几次'}];assert.deepEqual(normalizePlan(r,b).questions,[]);});

test('review adding useful questions clears an obsolete initial stop without changing hard guards',async()=>{let calls=0;const p=await planWithGapCheck(base(),{call:async()=>{calls++;return {result:calls===1?{...raw([]),stop:true}:{...raw(['G08']),questions:raw(['G08']).questions.map(q=>({...q,questionText:QUESTION_BY_ID[q.id].question})),stop:false,keepScenario:false,changeSubject:'self',evidence:base().hypotheticalDirection}};}});assert.equal(p.questions.length,1);assert.equal(p.stop,false);});
