import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {compileSetting,generationSetting} from '../src/effective-setting.js';import {storyMessages} from '../server/prompts.js';import {createCaller} from '../server/minimax.js';
import {participantIdentity,OPENING_AUDIENCE} from '../src/participant-identity.js';
const reading={birthYear:'2000',forkAge:'26',gender:'不透露',locationText:'南京',realityOutcome:'2026年我没有去读书会。',hypotheticalDirection:'2026年我去读书会，只看两个月。',details:'每月参加一次。只写阅读与交流，不依赖未提供的职业和家庭背景。'};
const pottery={...reading,realityOutcome:'2026年我没有继续学陶艺。',hypotheticalDirection:'2026年我继续学陶艺，只看两个月。',details:'每月两次，遇到困难先自己试。',followupKey:'model',followupQuestion:'重新捡起还是接着当时课程？',followupAnswer:'',followupSkipped:'1'};
test('supported self-protagonist request keeps original actor, audience and source constraints',()=>{for(const b of [reading,pottery]){const m=storyMessages(b,'',false),p=JSON.parse(m[1].content);assert.deepEqual(p.identityMap,participantIdentity());assert.deepEqual(p.identityMap.user.id,OPENING_AUDIENCE.recipient);assert.equal(p.effectiveSetting.sources.find(s=>s.id==='hypotheticalDirection').text,b.hypotheticalDirection);assert.ok(p.effectiveSetting.sources.some(x=>x.id==='details'&&x.text===b.details));assert.ok(!m[0].content.includes('两者不必是同一个人的两条人生'));assert.ok(!p.effectiveSetting.sourceScope);assert.ok(m[0].content.includes('主角始终是现实用户的另一个自己'));}});
test('unknown-month coarse end year is not sent as an observation deadline',()=>{const c=compileSetting(reading),g=generationSetting(c);assert.equal(c.temporal.window.end.year,2027);assert.equal(g.temporal.start.year,2026);assert.equal(g.temporal.window.start.year,2026);assert.equal(g.temporal.window.end,null);assert.equal(g.temporal.window.months,2);assert.equal(g.temporal.window.calendarBoundsKnown,false);assert.equal(c.temporal.window.end.year,2027);});
test('explicit calendar bounds stay intact',()=>{const b={...reading,realityOutcome:'2026年9月没有去读书会。',hypotheticalDirection:'2026年9月去读书会，只看两个月。'},c=compileSetting(b);assert.deepEqual(generationSetting(c).temporal,c.temporal);assert.equal(c.temporal.window.end.month,11);});
test('skipped pottery question remains unknown, cannot become an answer',()=>{const p=JSON.parse(storyMessages(pottery,'',false)[1].content);assert.equal(p.canClarify,false);assert.deepEqual(p.effectiveSetting.unknownBackground.latestConfirmation,{question:pottery.followupQuestion,skipped:true,answerRefs:[]});assert.ok(!p.effectiveSetting.sources.some(s=>s.id==='followupAnswer'));assert.ok(storyMessages(pottery)[0].content.includes('跳过'));});
test('actual outgoing request keeps constraints without network',async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'request115-'));try{for(const b of [reading,pottery]){let captured;const messages=storyMessages(b,'',false),caller=createCaller({mode:'real',model:'offline',site:'cn',base:'https://offline.invalid',key:'offline'},{directory,env:{REQUEST_DIAGNOSTICS:'0'},fetchImpl:async(u,o)=>{captured=JSON.parse(o.body);throw Error('capture only');}});await assert.rejects(caller.call('story',messages),e=>e.category==='network');assert.deepEqual(captured.messages,messages);assert.equal(captured.tools.length,1);assert.equal(captured.tools[0].function.name,'submit_story');assert.equal(JSON.parse(captured.messages[1].content).effectiveSetting.constraints.observation.window.end,null);}}finally{fs.rmSync(directory,{recursive:true,force:true});}});

