import test from 'node:test';import assert from 'node:assert/strict';
import {applyClarification,hardQuestion,timeAnchors} from '../src/input-anchors.js';import {ageFieldErrors} from '../src/age-validation.js';import {compileSetting,generationSetting} from '../src/effective-setting.js';import {normalizeMemoryResult} from '../server/memory-extraction.js';import {applyMemoryOperations} from '../src/memory-operations.js';import {streamingChatMessages} from '../server/prompts.js';import {demoStory} from '../src/services/demo.js';
const b={birthYear:'2000',forkAge:'22',gender:'不透露',mbti:'unknown',realityOutcome:'2022年我20或22岁，去了青岛又一直留济南。我当时养了一只猫。',hypotheticalDirection:'假设去青岛工作，又想留在济南',followupKey:'hard-conflict',followupAnswer:''};
test('all conflicts + natural answer compiled once, retains unrelated source, no conflict reflow',()=>{const q=hardQuestion(b);assert.match(q.question,/几岁/);assert.match(q.question,/去了哪里/);assert.match(q.question,/离开/);const r=applyClarification({...b,followupAnswer:'2022年22岁，现实留济南读研，假设去青岛工作，随后三个月'});assert.equal(hardQuestion(r),null);assert.deepEqual(ageFieldErrors(r),{});assert.match(r.realityOutcome,/养了一只猫/);assert.deepEqual(applyClarification(r),r);const payload=JSON.stringify(generationSetting(compileSetting(r)));assert.ok(!payload.includes('20或22'));assert.equal(timeAnchors(r).window.months,3);assert.match(r.clarificationOriginal,/20或22/);});
test('city variant + unresolved correction remains question',()=>{const v={...b,realityOutcome:b.realityOutcome.replaceAll('青岛','厦门').replaceAll('济南','福州'),hypotheticalDirection:b.hypotheticalDirection.replaceAll('青岛','厦门').replaceAll('济南','福州')};assert.match(hardQuestion({...v,followupAnswer:'现实留福州读研'}).question,/几岁/);const r=applyClarification({...v,followupAnswer:'2022年22岁，现实留福州读研，假设去厦门工作，随后三个月'});assert.equal(hardQuestion(r),null);assert.match(r.hypotheticalDirection,/厦门/);});
const l=()=>({id:'L',memories:[],sessionMeta:{},messages:[{id:'u',role:'user',text:'朋友小夏每周练口琴，我养了仓鼠豆包，我每周六学攀岩。'}]});
const op=(x={})=>({kind:'add',subject:'user',timeState:'current',subjectEvidence:'我',targetId:null,sourceId:'u',type:'reality',text:'养了仓鼠豆包',evidence:'我养了仓鼠豆包',needsConfirmation:false,...x});
test('source is not subject; mixed clause preserves user/pet and excludes third person/unknown',()=>{const life=l(),d={lifeId:'L',messages:life.messages,memories:[]};const r=normalizeMemoryResult({operations:[op(),op({subject:'third_party',text:'练口琴'}),op({subject:'unknown'}),op({subjectEvidence:'朋友小夏',evidence:'朋友小夏每周练口琴',text:'每周练口琴'})]},d,'b');assert.equal(r.operations.length,1);assert.equal(applyMemoryOperations(life,r).memories.length,1);});
test('batch and saved duplicate converge with sources, operations idempotent',()=>{const life=l();life.messages.push({id:'u2',role:'user',text:'我养了仓鼠豆包。'});life.memories=[{id:'existing',text:'养了仓鼠豆包。',type:'reality',sourceId:'u'}];const r=normalizeMemoryResult({operations:[op({sourceId:'u2'}),op({sourceId:'u2',text:' 养了仓鼠豆包。 '})]}, {lifeId:'L',memories:life.memories,messages:life.messages},'b');const next=applyMemoryOperations(life,r);assert.equal(next.memories.length,1);assert.equal(next.memories[0].id,'existing');assert.deepEqual(next.memories[0].sources,['u','u2']);assert.equal(applyMemoryOperations(next,r).memories.length,1);});
test('different name and interest not dropped with user same sentence',()=>{const life=l();life.messages[0].text='同事阿林喜欢陶艺，我每周日学游泳。';const r=normalizeMemoryResult({operations:[op({subject:'third_party'}),op({text:'每周日学游泳',evidence:'我每周日学游泳'})]}, {lifeId:'L',memories:[],messages:life.messages},'b');assert.equal(r.operations.length,1);});
test('actual chat messages map three identities and remove pre-correction assistant claims and role records',()=>{for(const scene of ['我下雨天没有去赴朋友的约','我没有参加同事合作']){const session={background:{...b,realityOutcome:scene,hypotheticalDirection:'这次我去了',followupKey:'',followupAnswer:''},story:{...demoStory,character:'我和朋友见面',opening:'那次我等到了朋友'},memories:[],history:[{role:'assistant',content:'你当时在星巴克门口等我。'},{role:'user',content:'你说错了，等你的是朋友，不是我。'}],roleRecords:[{text:'你在星巴克门口等我',kind:'statement'}]};const sent=streamingChatMessages(session,'后来呢？','chat'),payload=JSON.parse(sent[1].content);assert.equal(payload.identityMap.user.id,'realUser');assert.equal(payload.identityMap.assistant.id,'parallelCharacter');assert.equal(payload.roleRecords.length,0);assert.ok(!sent.some(m=>m.role==='assistant'));assert.match(payload.identityCorrections[0].text,/不是我/);}});


test('event April and observation May-June are separate, ordinary future event remains start',()=>{const a=timeAnchors({realityOutcome:'2026年4月评选，表弟入选，我未入选',hypotheticalDirection:'仅我入选，表弟未入选且不参与策展，观察2026年5—6月'});assert.equal(a.start.month,4);assert.equal(a.window.start.month,5);assert.equal(a.window.end.month,6);assert.equal(timeAnchors({realityOutcome:'现在在成都',hypotheticalDirection:'2027年4月去大理驻留半年'}).start.month,4);});
import {modelHistory} from '../src/life-store.js';import {roleRecords} from '../src/role-record.js';import {explicitCorrections} from '../src/consistency.js';import {dedupeMemories} from '../src/memory-operations.js';
test('ownership correction survives recent-history truncation; dedupe leaves inputs untouched and worlds separate',()=>{const messages=[{id:'a',role:'assistant',text:'我和你在门口等了一小时。'},{id:'u',role:'user',text:'你说错了，等你的是同事，不是我。',status:'sent'},...Array.from({length:14},(_,i)=>({id:'u'+i,role:'user',text:'继续聊',status:'sent'}))];assert.equal(modelHistory(messages).some(m=>m.role==='assistant'),false);assert.equal(roleRecords(messages,b).length,0);assert.equal(explicitCorrections(messages)[0].type,'identity');const rows=[{id:'1',type:'reality',text:'学攀岩',sourceId:'u'},{id:'2',type:'reality',text:'学攀岩。',sourceId:'v'},{id:'3',type:'fiction',text:'学攀岩'}];const before=JSON.stringify(rows);const next=dedupeMemories(rows);assert.equal(next.length,2);assert.equal(JSON.stringify(rows),before);});
