import test from 'node:test';import assert from 'node:assert/strict';
import {beijingNow,REALTIME_RULE} from '../server/realtime-context.js';
import {storyMessages,chatMessages,streamingChatMessages} from '../server/prompts.js';
import {demoStory} from '../src/services/demo.js';
const background={birthYear:'2000',forkAge:'25',gender:'不透露',mbti:'unknown',locationText:'南京',realityOutcome:'2025年9月没有报名。',hypotheticalDirection:'如果报名陶艺课，只看9月和10月。'};
test('Beijing afternoon and midnight use UTC+8 regardless of host zone',()=>{assert.equal(beijingNow(new Date('2026-09-26T09:15:00Z')).time,'17:15');assert.equal(beijingNow(new Date('2026-09-26T16:01:00Z')).date,'2026-09-27');assert.equal(beijingNow(new Date('2026-09-26T16:01:00Z')).time,'00:01');});
test('opening, normal, stream and recall have fresh real time without moving story clock',()=>{const s={background,story:demoStory,history:[],memories:[]},now=new Date('2026-09-26T09:15:00Z');const opening=storyMessages(background,'',true,undefined,null,now);assert.equal(JSON.parse(opening[1].content).realWorldNow.time,'17:15');assert.ok(opening[0].content.includes(REALTIME_RULE));for(const text of ['接着聊吧','你记得我学了什么吗？']){const a=chatMessages(s,text,'chat',now),b=streamingChatMessages(s,text,'chat',now),next=chatMessages(s,text,'chat',new Date('2026-09-26T10:25:00Z'));assert.deepEqual(a.slice(1),b.slice(1));for(const m of [a,b]){assert.ok(m[0].content.includes(REALTIME_RULE));assert.equal(JSON.parse(m[1].content).realWorldNow.time,'17:15');}assert.equal(JSON.parse(next[1].content).realWorldNow.time,'18:25');assert.deepEqual(JSON.parse(a[1].content).chatTime,JSON.parse(next[1].content).chatTime);}});

import {directBeijingReply} from '../server/realtime-context.js';
import {createExperience} from '../server/experience.js';
test('standalone clock questions use fresh Beijing values; story event questions remain story questions',()=>{for(const q of ['现在几点了？','你知道现在几点吗？','北京时间现在几点？','几点了']){assert.equal(directBeijingReply(q,new Date('2026-09-26T09:15:00Z')),'北京时间现在是17:15。');assert.equal(directBeijingReply(q,new Date('2026-09-26T14:05:00Z')),'北京时间现在是22:05。');}for(const q of ['故事里现在几点？','那次上课是几点？','我现在几点睡比较好？','晚上十点我再来'])assert.equal(directBeijingReply(q),null);assert.ok(directBeijingReply('现在几点',new Date('invalid')).includes('不猜'));});
test('clock replies pass through normal and streamed history/seen flow without calling model',async()=>{let calls=0;const app=createExperience({mode:'real',maxConcurrent:3},{call:async()=>{calls++;throw Error('unexpected model call');}});const {sessionId}=app.restore({snapshot:{background,story:{...demoStory,kind:'story',character:demoStory.intro,opening:'刚下课。'},history:[],memories:[]}});const r=await app.chat({sessionId,message:'现在几点了？'});assert.match(r.reply,/北京时间现在是\d{2}:\d{2}/);const events=[];await app.chatStream({sessionId,message:'北京时间现在几点？'},e=>events.push(e),new AbortController().signal);assert.deepEqual(events.map(e=>e.type),['start','text','done']);assert.match(events[1].text,/北京时间现在是/);assert.deepEqual(app.seen({sessionId,turnId:events[0].turnId,text:events[1].text}),{ok:true});assert.equal(calls,0);});
