import {AppError} from './core.js';
import {supplementState,answerText,unknownAnswer} from '../src/supplementary.js';
import {QUESTION_BY_ID} from '../src/question-bank.js';
export const QUESTION_SELECTION_RULE='先做逐题反证：尝试用sources中的已有原话回答候选题。若已经能回答，就在covered中给出题ID、sourceId和逐字evidence并移除该题；不要因为答案没有以选项原句出现就判未知。一句话可覆盖兴趣位置、投入节奏、受挫处理等多个维度；例如固定留时间已说明投入位置，画不出来先自己试已说明第一应对步骤。只评估剩余缺口，不把已知换成抽象问题重问。先按本次原文筛出最多6个相关且未回答的候选，按信息增量由高到低排序，页面只取前3个。每项返回informationGain:0至3（0已回答、重复或无关；1仅增加标签、布景或零碎小动作；2会改变本次主题相关的具体选择、相处方式或生活安排；3会明显改变用户在意的关键行动），missingInformation写具体尚缺什么，useInStory说明不同答案会怎样改变该行动，不能只说更丰富或更具体。分数是判断而非事实；只有未回答且值得让用户补充的2至3分题才保留，0至3题都正常，不以3题为目标。已经提供的行为可以回答问题时就结束该维度，不以还能问得更细为由追问。只为描写落座、摆工具等日常动作而找问题，通常属于创作空间；除非原文明确在意这项行动，不升级为高价值缺口。生活作息与关系反应不是同一维度，但只在关系反应与本次主题相关时才考虑追问。先看主题相关与答案是否已有，再评估增量，不问所有人同一套。questions按分数降序列候选，程序按同维度择一、最多3题和剩余额度裁剪。不能为故事制造困难来让问题变有用。';
export const QUESTION_STOP_RULE='selectionState是程序给出的停止边界：remaining为0、scenario存在或currentGroupSkipped为true时不得追加普通题或情景题，审查不得推翻；有情景回答只分析原回答。skippedDimensions不换问法追问。软停止（觉得信息已够）可重新审查，但不推翻用户跳过、已展示维度、题数上限或情景结束。两阶段沿用answerContexts与confirmations，确认已解决的冲突不重问。';
export function questionSelectionState(b){const s=supplementState(b),ids=s.pages?.[s.page]||s.shown;const currentGroupSkipped=ids.length>0&&ids.every(id=>{const a=s.answers[id];return a&&(a.skipped||unknownAnswer(answerText(a)));});return {remaining:Math.max(0,8-s.shown.length),shown:s.shown,scenario:s.scenario?{id:s.scenario.id,skipped:s.scenario.skipped,answered:Boolean(s.scenario.answer?.trim())}:null,currentGroupSkipped,skippedDimensions:[...new Set(Object.entries(s.answers).filter(([,a])=>a.skipped||unknownAnswer(answerText(a))).map(([id])=>QUESTION_BY_ID[id]?.group).filter(Boolean))],answerContexts:s.answerScopes||{},confirmations:s.confirmations||[]};}
export function rankQuestions(questions){return questions.map((q,index)=>({q,index})).filter(({q})=>q.informationGain==null||Number.isInteger(q.informationGain)&&q.informationGain>=2&&q.informationGain<=3&&typeof q.missingInformation==='string'&&q.missingInformation.trim()&&typeof q.useInStory==='string'&&q.useInStory.trim()).sort((a,b)=>(b.q.informationGain??2)-(a.q.informationGain??2)||a.index-b.index).map(({q})=>q);}

export function validateQuestionAssessments(raw){if(!Array.isArray(raw?.questions)||raw.questions.some(q=>!q||!Number.isInteger(q.informationGain)||q.informationGain<0||q.informationGain>3||typeof q.missingInformation!=='string'||!q.missingInformation.trim()||q.missingInformation.length>300||typeof q.useInStory!=='string'||!q.useInStory.trim()||q.useInStory.length>300))throw new AppError('invalid_response',502,{reason:'question_information_assessment_missing'});return raw;}
