import {AppError} from './core.js';
import {supplementState,answerText,unknownAnswer} from '../src/supplementary.js';
import {QUESTION_BY_ID} from '../src/question-bank.js';
export const QUESTION_SELECTION_RULE='先按本次原文筛出最多6个相关且未回答的候选，按信息增量由高到低排序，页面只取前3个。每项返回informationGain:0至3（0重复或无关；1只有标签或作用很小；2补足具体行动条件；3明显区分人物做法），missingInformation写尚缺什么，useInStory写答案会改变哪个具体行动或关系细节。分数是基于原文的判断，不是客观测量；不能为凑数抬分。只考虑2至3分；有3个互不重复的有用缺口就优先问3题，只有1至2个就少问，充分才0题。生活作息已知不等于具体反应已知。先看主题相关与答案是否已有，再评估增量，不问所有人同一套。questions按分数降序列候选，程序按同维度择一、最多3题和剩余额度裁剪。不能为故事制造困难来让问题变有用。';
export const QUESTION_STOP_RULE='selectionState是程序给出的停止边界：remaining为0、scenario存在或currentGroupSkipped为true时不得追加普通题或情景题，审查不得推翻；有情景回答只分析原回答。skippedDimensions不换问法追问。软停止（觉得信息已够）可重新审查，但不推翻用户跳过、已展示维度、题数上限或情景结束。两阶段沿用answerContexts与confirmations，确认已解决的冲突不重问。';
export function questionSelectionState(b){const s=supplementState(b),ids=s.pages?.[s.page]||s.shown;const currentGroupSkipped=ids.length>0&&ids.every(id=>{const a=s.answers[id];return a&&(a.skipped||unknownAnswer(answerText(a)));});return {remaining:Math.max(0,8-s.shown.length),shown:s.shown,scenario:s.scenario?{id:s.scenario.id,skipped:s.scenario.skipped,answered:Boolean(s.scenario.answer?.trim())}:null,currentGroupSkipped,skippedDimensions:[...new Set(Object.entries(s.answers).filter(([,a])=>a.skipped||unknownAnswer(answerText(a))).map(([id])=>QUESTION_BY_ID[id]?.group).filter(Boolean))],answerContexts:s.answerScopes||{},confirmations:s.confirmations||[]};}
export function rankQuestions(questions){return questions.map((q,index)=>({q,index})).filter(({q})=>q.informationGain==null||Number.isInteger(q.informationGain)&&q.informationGain>=2&&q.informationGain<=3&&typeof q.missingInformation==='string'&&q.missingInformation.trim()&&typeof q.useInStory==='string'&&q.useInStory.trim()).sort((a,b)=>(b.q.informationGain??2)-(a.q.informationGain??2)||a.index-b.index).map(({q})=>q);}

export function validateQuestionAssessments(raw){if(!Array.isArray(raw?.questions)||raw.questions.some(q=>!q||!Number.isInteger(q.informationGain)||q.informationGain<0||q.informationGain>3||typeof q.missingInformation!=='string'||!q.missingInformation.trim()||q.missingInformation.length>300||typeof q.useInStory!=='string'||!q.useInStory.trim()||q.useInStory.length>300))throw new AppError('invalid_response',502,{reason:'question_information_assessment_missing'});return raw;}
