import React,{useEffect,useRef,useState} from 'react';
import {historyCandidates,historyNodeLabel,applyHistoryReuse,historySources} from './history-reuse.js';
export default function HistoryReuseDialog({lives,background,onApply,onClose}){
 const sources=historySources(lives);
 const [source,setSource]=useState(sources.at(-1)?.id||sources[0]?.id||''),[selected,setSelected]=useState([]),[error,setError]=useState(''),dialog=useRef(null);
 const life=lives.find(l=>l.id===source),candidates=life?historyCandidates(life):[];
 useEffect(()=>{dialog.current.showModal();return()=>dialog.current?.close();},[]);
 useEffect(()=>{setSelected(candidates.filter(e=>e.defaultSelected).map(e=>e.id));setError('');},[source]);
 return <dialog className="supplement-dialog history-reuse-dialog" ref={dialog} aria-label="复用历史填写" onCancel={e=>{e.preventDefault();onClose();}}><header><h2>带入以前写过的内容</h2><button type="button" className="text-button" onClick={onClose}>关闭，重新填写</button></header><div className="supplement-scroll"><label className="field">选择一份历史填写<select value={source} onChange={e=>setSource(e.target.value)}>{sources.map((l,i)=><option key={l.id} value={l.id}>{i===sources.length-1?'最近一次 · ':''}{historyNodeLabel(l)}</option>)}</select></label><p className="small">只带入勾选项，填入后都能修改。原历史不会改变。本次经过、替代选择和故事约束默认不选。</p><p className="small">城市、生活状态、关系和习惯可能随年龄改变。勾选表示你已核对它适用于本次；原回答的节点和时间仍保留。追问答案请在写好本次故事起点后带入，之后更换起点会暂停使用。</p>{candidates.map(e=><section key={e.id} className="reuse-item"><label><input type="checkbox" checked={selected.includes(e.id)} onChange={()=>setSelected(s=>s.includes(e.id)?s.filter(id=>id!==e.id):[...s,e.id])}/>{e.question} {e.kind==='answer'?'（原追问）':''}</label><p className="small">来源：{e.sourceNode.forkAge||'未填'}岁 · {e.sourceTime}</p>{e.selected.length>0&&<p>原选择：{e.selected.join('；')}</p>}{e.text.length>160?<details><summary>{e.text.slice(0,160)}…（展开原回答）</summary><p>{e.text}</p></details>:e.text&&<p>原回答：{e.text}</p>}</section>)}{!candidates.length&&<p>这份历史没有可复用的填写内容。</p>}{error&&<p role="alert">{error}</p>}</div><div className="am-followup-actions"><button type="button" className="primary" disabled={!selected.length} onClick={()=>{if(selected.some(id=>id.startsWith('answer:'))&&(!background.realityOutcome.trim()||!background.hypotheticalDirection.trim()||!background.forkAge)){setError('先写好本次现实经过、改变方向和年龄，再核对带入追问答案。');return;}try{onApply(applyHistoryReuse(background,candidates,selected));}catch{setError('这些填写无法带入，请减少勾选项或重新填写。');}}}>已核对，带入勾选内容</button></div></dialog>;
}
