import {storyText} from './story-text.js';
import MemoryFailureDetails from './MemoryFailureDetails.jsx';
import React,{useState} from 'react';
import {reviewStory} from './fact-frame.js';
import {archiveName} from './story-input';
import {sortedLives} from './postal-state.js';
function summary(l){const safe=reviewStory(l.story,l.background,l.memories||[]).trusted;const text=safe.intro||safe.scenes?.[0]?.text||'那次不同的开始，留下了一封来信。';return storyText(text).split(/[。！？]/)[0].slice(0,90)+'。';}
export default function LifeHome({library,onOpen,onNew,onDelete,onRename,notice}){
 const [selected,setSelected]=useState(null),[deleting,setDeleting]=useState(null),[renaming,setRenaming]=useState(null),[name,setName]=useState(''),[page,setPage]=useState(0);
 const ordered=sortedLives(library),pages=Math.max(1,Math.ceil(ordered.length/6)),current=Math.min(page,pages-1),items=ordered.slice(current*6,current*6+6);
 return <section className="life-home"><h1>我的那些如果</h1><p>每一条路，都可以接着聊。</p>{notice&&<p role="status">{notice}</p>}<button className="primary" onClick={onNew}>探索新的人生 ↗</button><div className="life-cards am-letter-stack">{items.map((l,i)=><article className={'life-card am-stack-card '+(selected===l.id?'is-selected':'')} style={{'--letter-tilt':(i%2?'.6deg':'-.6deg')}} key={l.id}>
 <button type="button" className="am-letter-select" aria-expanded={selected===l.id} aria-controls={'letter-actions-'+l.id} onClick={()=>{setSelected(selected===l.id?null:l.id);setDeleting(null);setRenaming(null);}}><span className="am-cover-postmark">平行邮局 · {String(current*6+i+1).padStart(2,'0')}</span><h2>{archiveName(l)}</h2><p>{summary(l)}</p><span className="small">{selected===l.id?'收起这封信 ↑':'选择这封信 ↗'}</span></button>
 {selected===l.id&&<div id={'letter-actions-'+l.id} className="am-letter-actions">{l.sessionMeta?.lastChatAt&&<p className="small">最近聊天：{new Date(l.sessionMeta.lastChatAt).toLocaleString('zh-CN')}</p>}{l.sessionMeta?.review?.status==='failed'&&<p role="alert">记忆整理未完成，请打开资料与记忆处理。</p>}{l.sessionMeta?.review?.status==='empty'&&<p role="status">本次未提取到事实卡，已保留待整理位置。</p>}<MemoryFailureDetails meta={l.sessionMeta}/>{l.sessionMeta?.conversationSummary?.length>0&&<p className="small">聊天总结已覆盖 {l.sessionMeta.conversationSummary.length} 条发言，其中 {l.sessionMeta.conversationSummary.filter(r=>r.mode!=='summary').length} 条为待归纳摘录。</p>}{<button className="text-button" onClick={()=>onOpen(l.id,'about')}>资料与记忆（{l.memories?.length||0}）</button>}{l.candidates?.length>0&&<p className="small">有 {l.candidates.length} 条待处理内容</p>}<div className="card-actions"><button className="primary" onClick={()=>onOpen(l.id,'chat')}>继续聊天</button><button className="text-button" onClick={()=>onOpen(l.id,'life')}>查看故事</button><details className="card-more"><summary>更多</summary><button className="text-button" onClick={()=>onOpen(l.id,'about')}>管理资料与记忆</button><button className="text-button" onClick={()=>{setRenaming(l.id);setName(archiveName(l));}}>改名</button><button className="text-button" onClick={()=>setDeleting(l.id)}>删除</button></details></div>{renaming===l.id&&<form onSubmit={e=>{e.preventDefault();if(name.trim()){onRename(l.id,name.trim());setRenaming(null);}}}><label>故事名称<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><button className="text-button">保存名称</button></form>}{deleting===l.id&&<div className="delete-confirm"><p>删除这条人生的故事、聊天、记忆和候选？其他人生不受影响。</p><button className="text-button" onClick={()=>{onDelete(l.id);setDeleting(null);setSelected(null);}}>确认删除这条人生</button><button className="text-button" onClick={()=>setDeleting(null)}>取消</button></div>}</div>}
 </article>)}</div>{pages>1&&<nav className="am-stack-pages" aria-label="信件分页"><button className="text-button" disabled={current===0} onClick={()=>{setPage(current-1);setSelected(null);}}>上一组</button><span>{current+1} / {pages}</span><button className="text-button" disabled={current===pages-1} onClick={()=>{setPage(current+1);setSelected(null);}}>下一组</button></nav>}{!library.length&&<p>还没有故事，从一个想回到的瞬间开始吧。</p>}<details className="settings"><summary>设置</summary><p>仅保存在当前浏览器，清除数据后会丢失。</p></details></section>;
}
