import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {settingNote} from './setting-note.js';
import {PostalWaiting} from './PostalMotion';
import {StoryPaperFrame} from './StoryPaper';
import './style.css';import './postal-motion.css';
const note=settingNote({change:{text:"这次选择去学陶艺",source:{text:"这次选择去学陶艺"}},temporal:{window:{months:3,anchor:"now"}},retained:[]});
function Preview(){const [outcome,setOutcome]=useState(""); const simulate=(ms,fail=false)=>{setOutcome("");setSending(true);setTimeout(()=>{setSending(false);setOutcome(fail?"模拟失败：填写内容仍保留":"模拟回信已到，不等待便笺播完");},ms);};const [sending,setSending]=useState(false);const [run,setRun]=useState(0),[playing,setPlaying]=useState(false),[frame,setFrame]=useState('');useEffect(()=>{if(!playing||frame)return;const t=setTimeout(()=>setPlaying(false),1000);return()=>clearTimeout(t);},[playing,run,frame]);return <main style={{maxWidth:850,margin:'30px auto',padding:20}}><h1>邮局动画本地预览</h1><button onClick={()=>simulate(50)}>模拟快速成功</button><button onClick={()=>simulate(800,true)}>模拟失败</button><p role="status">{outcome}</p><button onClick={()=>setSending(true)}>预览折信寄出与等待</button>{sending&&<PostalWaiting settingNote={note} onCancel={()=>setSending(false)}/>}<p>不生成故事、不读取存档、不调用模型。正常播放总时长1秒；也可选择关键帧检查遮挡。</p><button onClick={()=>{setFrame('');setRun(n=>n+1);setPlaying(!matchMedia('(prefers-reduced-motion: reduce)').matches);}}>重播回信</button><label>检查阶段 <select value={frame} onChange={e=>{setFrame(e.target.value);setRun(n=>n+1);setPlaying(Boolean(e.target.value));}}><option value="">正常播放</option><option value="-.2s">落定</option><option value="-.5s">抽出中</option><option value="-.68s">完全离开信封</option><option value="-.84s">折页展开</option><option value="-.99s">衔接正文</option></select></label><div className={frame?'preview-paused':''} style={{'--frame':frame}}><StoryPaperFrame key={run} playing={playing} onSkip={()=>{setPlaying(false);setFrame('');}}><h2>那条路上的日常</h2><p>这是本地预览信纸。正文仍在原有阅读页完整显示，动画不会触发请求或保存。</p></StoryPaperFrame></div></main>};
if(import.meta.env.DEV)createRoot(document.getElementById('root')).render(<Preview/>);
