// User-selected hypothetical bank; original numbers preserved.
export const SCENARIO_BANK=[
  {
    "id": "Q01",
    "question": "你和朋友约好旅行，出发前一天，对方说：“最近实在太累了，想少去几个地方，多在酒店待着。”你很期待这次旅行，也做好了攻略。你会怎么回？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "shared-rhythm",
    "when": "旅行／关系",
    "purpose": "各自需要与共同安排；可参考协商方式。",
    "perspective": "self"
  },
  {
    "id": "Q03",
    "question": "朋友准备辞职开一家小店，兴致勃勃地跟你讲了装修和菜单，但还没算过成本。他问：“你觉得我能做起来吗？”你会怎么回答？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "risk-advice",
    "when": "工作／经营",
    "purpose": "支持他人与核实风险；不能等同本人风险偏好。",
    "perspective": "advice"
  },
  {
    "id": "Q04",
    "question": "你正准备换城市，家人说：“我们舍不得你，不过你想去就去，不用担心我们。”你会跟他们说什么？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "old-new-bonds",
    "when": "迁居／家庭",
    "purpose": "自主决定与保持联系；不预设内疚或家庭阻力。",
    "perspective": "self"
  },
  {
    "id": "Q05",
    "question": "一个很久没联系的朋友发来消息：“路过我们以前常去的那家店，发现还开着。要不要哪天一起去？”你们当初没有吵架，只是慢慢疏远了。你会怎么回？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "reconnect",
    "when": "朋友关系",
    "purpose": "重建联系的意愿与条件；可参考接近关系的方式。",
    "perspective": "self"
  },
  {
    "id": "Q06",
    "question": "朋友送了你一张演出票，是他很喜欢、你却不太感兴趣的类型。他说：“一直想带你看看，你应该会喜欢。”你会怎么回应？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "boundary",
    "when": "兴趣／关系",
    "purpose": "接受好意与个人喜好；可参考表达不同偏好的方式。",
    "perspective": "self"
  },
  {
    "id": "Q07",
    "question": "聚餐时，朋友提起一件你早已不想再被提起的糗事，其他人听得很开心。他转头说：“你自己讲，肯定更好笑。”你会怎么接这句话？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "boundary",
    "when": "朋友关系",
    "purpose": "边界与场合；可参考如何表达不愿配合。",
    "perspective": "self"
  },
  {
    "id": "Q08",
    "question": "同事邀请你一起报名一个新项目：“我们都没做过，不过可以边做边学。”你确实感兴趣，但最近刚把手头的事情理顺。你会怎么回复？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "opportunity-rhythm",
    "when": "工作／学习",
    "purpose": "新鲜感与现有节奏；可参考接受机会的条件。",
    "perspective": "self"
  },
  {
    "id": "Q09",
    "question": "你和搭档完成了一个作品，对方想马上发出去，你还想调整几个细节。他说：“再改下去，我们可能永远都发不了。”你会怎么回应？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "ready-act",
    "when": "创作／合作",
    "purpose": "质量与推进；可参考完成标准和协商方式。",
    "perspective": "self"
  },
  {
    "id": "Q10",
    "question": "朋友看了你最近画的几张画，问：“能不能帮我也画一张？就照这个感觉来，你随便画就行。”你不知道他期待的是一份礼物，还是一次正式委托。你会怎么回？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "expectation-boundary",
    "when": "兴趣／工作／关系",
    "purpose": "如何确认模糊期待；可参考时间和劳动边界。",
    "perspective": "self"
  },
  {
    "id": "Q11",
    "question": "你刚开始练一项运动，朋友说：“要不要一起报个比赛？有个目标，练起来更有劲。”你原本只是想活动活动。你会怎么回答？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "interest-investment",
    "when": "兴趣／运动",
    "purpose": "目标驱动与日常享受；可参考是否接受外加目标。",
    "perspective": "self"
  },
  {
    "id": "Q12",
    "question": "你告诉朋友自己拿到了一个期待很久的机会，他说：“恭喜！不过我也申请了，没选上，今天可能没法陪你庆祝。”你会怎么回？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "sharing-care",
    "when": "机会替换／朋友关系",
    "purpose": "分享喜悦与他人感受；不预设压抑喜悦才是好答案。",
    "perspective": "self"
  },
  {
    "id": "Q14",
    "question": "你刚搬到新城市，旧朋友说：“你最近讲的都是那边的事，我们这边的消息你都快跟不上了。”你会怎么回？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "old-new-bonds",
    "when": "迁居／朋友关系",
    "purpose": "新生活与旧联系；可参考关系维护的具体方式。",
    "perspective": "self"
  },
  {
    "id": "Q17",
    "question": "一个刚认识的人听说你的兴趣后，说：“这有什么用啊？”你听不出他是在认真问，还是随口打趣。你会怎么回答？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "value",
    "when": "兴趣／生活方式",
    "purpose": "如何理解兴趣的价值；保留对语气不确定的判断。",
    "perspective": "self"
  },
  {
    "id": "Q18",
    "question": "朋友想让你陪着做一件你试过、但不太喜欢的事。他说：“上次可能只是没碰到好玩的地方，再陪我试一次？”你会怎么回？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "boundary",
    "when": "兴趣／朋友关系",
    "purpose": "再尝试的条件与个人边界；不能等同固执或随和。",
    "perspective": "self"
  },
  {
    "id": "Q21",
    "question": "朋友认真听完你的烦恼，给了一个很完整的建议。你觉得有道理，但不想照着做。他问：“那你准备什么时候开始？”你会怎么回？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "boundary",
    "when": "关系／选择",
    "purpose": "对建议的自主权；可参考表达不同意的方式。",
    "perspective": "self"
  },
  {
    "id": "Q22",
    "question": "你参加了一次活动，组织者觉得你很适合带下次活动，问：“下次交给你怎么样？可以按你的想法来。”你原本只打算来玩。你会怎么回应？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "opportunity-rhythm",
    "when": "兴趣／社区活动",
    "purpose": "参与乐趣与承担责任；可参考接受角色变化的条件。",
    "perspective": "self"
  },
  {
    "id": "Q23",
    "question": "你选了一条收入普通、但自己挺喜欢的路。一个关心你的人说：“你明明可以争取更好的，会不会可惜？”你会怎么回答？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "value",
    "when": "工作／升学",
    "purpose": "对好生活的判断；不自动推断不重视收入或成就。",
    "perspective": "self"
  },
  {
    "id": "Q24",
    "question": "另一个你说：“我去了你当时没去的那座城市。这里确实有很多新鲜事，但我也开始想念以前那些熟悉的日子。”你最想回什么？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "old-new-bonds",
    "when": "迁居／生活变化",
    "purpose": "对新鲜与熟悉并存的看法；给他人的话不等同本人愿望。",
    "perspective": "advice"
  },
  {
    "id": "Q25",
    "question": "另一个你说：“那件你一直想试的事，我试了。没做出什么成绩，不过过程还挺开心。你会觉得这一趟值得吗？”你会怎么回答？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "value",
    "when": "兴趣／探索",
    "purpose": "过程与成果如何衡量；可参考对值得的明确解释。",
    "perspective": "advice"
  },
  {
    "id": "Q27",
    "question": "你报名了一门一直想学的课，上了几次后发现，最喜欢的部分只占课程的一小半。还剩六周，现在退出可以退一半费用。你会怎么做？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "interest-investment",
    "when": "兴趣／学习",
    "purpose": "兴趣变化与继续投入；可参考停止或调整的条件。",
    "perspective": "self"
  },
  {
    "id": "Q28",
    "question": "你突然多出一天假，朋友和家人都有安排，你也没有必须处理的事。预算够在附近玩一天，也可以全部留给自己。你最先会安排什么？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "rest",
    "when": "生活方式／休息",
    "purpose": "自由时间里主动选择的活动；不据此判定内外向。",
    "perspective": "self"
  },
  {
    "id": "Q29",
    "question": "你想申请一个机会，截止时间只剩两天。现有作品已经符合报名要求，但你觉得再花一周能做得更好；下一次开放申请要等半年。你会怎么处理？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "ready-act",
    "when": "升学／工作／创作",
    "purpose": "时机与准备程度；可参考提交或等待的理由。",
    "perspective": "self"
  },
  {
    "id": "Q30",
    "question": "你和朋友合租，客厅有一块空地方。你想放一张能做手工的大桌子，对方想放沙发，空间只能容纳一个。预算由两个人一起出。你会怎么推进这件事？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "shared-resources",
    "when": "合租／迁居",
    "purpose": "共同资源与不同需要；可参考决策和协商方式。",
    "perspective": "self"
  },
  {
    "id": "Q31",
    "question": "你正在学做饭，一道菜试了三次都不太成功。明天朋友来吃饭，食材已经买好，时间够再试一次，也够换一道熟悉的菜。你会怎么准备？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "setback",
    "when": "兴趣／日常",
    "purpose": "尝试与可靠完成；可参考是否分开处理练习和招待。",
    "perspective": "self"
  },
  {
    "id": "Q32",
    "question": "你在一次活动里认识了一个聊得很投机的人，交换联系方式后，一周都没再说话。今天看到一件你觉得对方会感兴趣的事。你会怎么做？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "reconnect",
    "when": "关系／活动",
    "purpose": "开启联系的具体方式与顾虑；不能只按主动与否分型。",
    "perspective": "self"
  },
  {
    "id": "Q33",
    "question": "你刚换到一份新工作，发现大家惯用的方法比较麻烦，而你知道一个更省事的办法。不过你还没弄清他们为什么一直这样做。你会先做什么？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "unfamiliar",
    "when": "工作／团队",
    "purpose": "了解背景与提出改变的顺序；可参考进入新环境的行动。",
    "perspective": "self"
  },
  {
    "id": "Q34",
    "question": "你在二手店发现一件很喜欢的旧物，价格在预算内，但带回家需要腾出一块地方，还得花些时间修整。你会怎么决定要不要买？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "cost",
    "when": "兴趣／生活方式",
    "purpose": "喜欢与维护负担；可参考愿意投入的条件。",
    "perspective": "self"
  },
  {
    "id": "Q35",
    "question": "你报名参加一个小型表演，临近上场，组织者说可以照常上，也可以换到下一场。你的准备足够完成，但还达不到自己满意的程度。你会怎么选？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "ready-act",
    "when": "兴趣／表现机会",
    "purpose": "尝试与准备标准；可参考上场或延期的条件。",
    "perspective": "self"
  },
  {
    "id": "Q36",
    "question": "你一直想尝试经营旧书摊，终于借到一个周末摊位。能带的书有限：一部分是你特别喜欢的冷门书，一部分是比较容易卖出去的热门书。你会怎么挑这一批书？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "creation-audience",
    "when": "经营／兴趣",
    "purpose": "个人偏好与他人需求；可参考分配方式而非二选一标签。",
    "perspective": "self"
  },
  {
    "id": "Q37",
    "question": "你和朋友一起旅行，中途发现一个很想停留的小镇。多住一天就得放弃后面一个已经订好的活动，费用只能退一半，朋友觉得两种安排都可以。你会怎么决定？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "plan-change",
    "when": "旅行／迁居",
    "purpose": "临时发现与既定投入；可参考改变计划的条件。",
    "perspective": "self"
  },
  {
    "id": "Q38",
    "question": "你收到一笔意料之外的小奖金，足够买一件惦记很久的东西，也足够报一门感兴趣的课。近期没有急用钱的地方。你会怎么用这笔钱？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "cost",
    "when": "机会／生活方式",
    "purpose": "自主分配资源的优先项；允许存下或另作安排。",
    "perspective": "self"
  },
  {
    "id": "Q39",
    "question": "你参加一个小组活动，大家意见不同，讨论了很久。你有一个折中的办法，但它会删掉你自己最喜欢的部分。你会怎么参与接下来的讨论？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "shared-resources",
    "when": "合作／学习",
    "purpose": "个人偏好与集体推进；可参考愿意妥协的条件。",
    "perspective": "self"
  },
  {
    "id": "Q40",
    "question": "你终于有机会回到生活过的老地方，但只能停留半天。你想去看看几个熟悉的地点，也有一位多年没见的人住在那里。你会怎么安排？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "old-new-bonds",
    "when": "迁居／关系",
    "purpose": "有限时间里在意的人与地方；不预设见人更有意义。",
    "perspective": "self"
  },
  {
    "id": "Q41",
    "question": "你把一个做好的作品发了出去，反响最好的是你随手加上的部分，自己最用心的部分却几乎没人提。接下来还有时间再做一个。你会怎么开始下一个作品？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "creation-audience",
    "when": "创作／兴趣",
    "purpose": "外部反馈与个人兴趣；可参考吸收反馈的具体方式。",
    "perspective": "self"
  },
  {
    "id": "Q42",
    "question": "你和朋友约好每周一起运动，最近发现两个人的节奏差得越来越远。一起练仍然开心，但各自练可能更适合目前的目标。你会怎么调整？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "shared-rhythm",
    "when": "运动／关系",
    "purpose": "个人节奏与共同活动；可参考如何保持关系又调整安排。",
    "perspective": "self"
  },
  {
    "id": "Q44",
    "question": "你原本打算独自完成一个小项目，做到一半，有人想加入。他擅长的部分正好能帮上忙，但也带来一些与你不同的想法。你会怎么安排这次合作？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "cooperation",
    "when": "工作／创作",
    "purpose": "自主权与合作收益；可参考分工和决策边界。",
    "perspective": "self"
  },
  {
    "id": "Q46",
    "question": "你参加一门兴趣课，老师提出可以参加进阶班，但需要每周多投入一个晚上。你目前学到的内容已经够日常玩了，也确实好奇接下来还能学什么。你会怎么考虑？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "interest-investment",
    "when": "兴趣／学习",
    "purpose": "深入学习与生活投入；可参考兴趣发展的节奏。",
    "perspective": "self"
  },
  {
    "id": "Q47",
    "question": "你和一个朋友有点疏远，终于约好见面。见面后两个人聊得挺开心，却一直没提之前让关系变淡的那件事，眼看就要分别了。你会怎么做？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "reconnect",
    "when": "朋友关系",
    "purpose": "修复关系与开启难题的时机；不预设必须谈开或和好。",
    "perspective": "self"
  },
  {
    "id": "Q48",
    "question": "你搬家时找到一箱旧笔记和小物件，大部分已经用不上，有些看到才想起当时的事情。新住处空间有限，但也不至于完全放不下。你会怎么整理这箱东西？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "old-new-bonds",
    "when": "迁居／生活变化",
    "purpose": "留存回忆与现实空间；可参考保留或处理的方式。",
    "perspective": "self"
  },
  {
    "id": "Q49",
    "question": "你有机会在另一个城市住一个月，住宿已经安排好，日常开销也没有压力。你希望回来时能说得出自己在那里生活过。到了之后，你最想先做哪件事？",
    "kind": "text",
    "options": [],
    "scenario": true,
    "group": "unfamiliar",
    "when": "迁居／未来体验",
    "purpose": "对生活感和融入的具体理解；只能参考回答中的行动偏好。",
    "perspective": "self"
  }
];
export const SCENARIO_BY_ID=Object.fromEntries(SCENARIO_BANK.map(q=>[q.id,q]));
