import {questionMeaning} from './question-meaning.js';
import {validSelections} from './question-options.js';
import {activeReusedAnswers,reuseProvenance,activeReuseEntries} from './history-reuse-data.js';
import {LIFE_BACKGROUND_FIELDS,lifeBackgroundEntries} from './life-background.js';
import {KEY_QUESTION_BY_ID,validCriticalGap,settingRecord} from './critical-background.js';
import {questionTime,questionTitle} from './question-context.js';
import {SCENARIO_BY_ID} from './scenario-bank.js';
import {scenarioReferences} from './scenario-context.js';
import {QUESTION_BY_ID as BANK_BY_ID} from './question-bank.js';
const ORDINARY_BY_ID={...BANK_BY_ID,...KEY_QUESTION_BY_ID};
const QUESTION_BY_ID={...ORDINARY_BY_ID,...SCENARIO_BY_ID};
export const unknownAnswer=text=>/^(?:我也?不(?:知道|清楚|确定)|不知道|不清楚|不确定|说不清|没想好|还没想好|随便|都可以|不想回答|跳过|说不清／不愿透露)[。！!？?\s]*$/.test(String(text||'').trim());
export function finishSupplementPage(state,ids){ids=ids.filter(id=>!SCENARIO_BY_ID[id]);const answers={...state.answers};for(const id of ids){const a=answers[id]||{selected:[],text:'',skipped:false};if(!answerText(a)||unknownAnswer(answerText(a)))answers[id]={...a,skipped:true};}return {...state,answers};}
const baseFields=['realityOutcome','hypotheticalDirection','birthYear','forkAge','locationText','gender','mbti','lifeSituation','choiceReason','details','additionalInfo','followupAnswer'];
export function supplementKey(b){const extra=[...LIFE_BACKGROUND_FIELDS,'additionalInfo','historyReuse'].filter(k=>b[k]).map(k=>[k,b[k]]);const text=JSON.stringify([...baseFields.map(k=>b[k]||''),...(extra.length?[extra]:[])]);let a=2166136261,c=5381;for(const x of text){a=Math.imul(a^x.charCodeAt(0),16777619);c=Math.imul(c,33)^x.charCodeAt(0);}return (a>>>0).toString(16)+(c>>>0).toString(16);}
const blank=()=>({shown:[],answers:{},pages:[],page:0,questionMeta:{},criticalUnknowns:[],confirmations:[],extra:'',plan:null,scenario:null,recentScenarios:[]});
function envelope(b){try{const x=JSON.parse(b.supplementary||'{}');return x&&Array.isArray(x.contexts)?x:{contexts:[]};}catch{return {contexts:[]};}}
export function supplementState(b){const contexts=envelope(b).contexts,exact=contexts.find(x=>x.key===supplementKey(b));if(exact)return exact.state;if(b.followupKey==='model'&&b.followupQuestion){const basis=supplementKey({...b,followupAnswer:''}),carried=contexts.find(x=>x.basis===basis||x.key===basis);if(carried)return {...carried.state,...(carried.state.scenario?{scenario:{...carried.state.scenario,analysis:null}}:{})};}return {...blank(),recentScenarios:contexts[0]?.state?.recentScenarios||[]};}
export function saveSupplement(b,state){const key=supplementKey(b),old=envelope(b);return {...b,supplementary:JSON.stringify({contexts:[{key,basis:supplementKey({...b,followupAnswer:''}),state},...old.contexts.filter(x=>x.key!==key)].slice(0,3)})};}
export function recordSupplementConfirmation(state,text){
 const answer=text.trim(),conflict=state.plan?.conflict,gaps=state.criticalUnknowns?.length?state.criticalUnknowns:state.plan?.criticalUnknowns||[];
 const gapKeys=conflict?.kind==='critical_background'?gaps.filter(g=>g.questionText===conflict.question).map(g=>g.key):[];
 return {...state,confirmations:[...state.confirmations,answer],confirmationContexts:[...(state.confirmationContexts||[]),{sourceIndex:state.confirmations.length,question:conflict?.question||'',gapKeys}].slice(0,2)};
}
export function answerText(a){if(!a||a.skipped)return '';return [...(a.selected||[]).filter(x=>x!=='自己定起止时间'),a.text||''].filter(Boolean).join('；');}
export function supplementSources(b){const s=supplementState(b);return [...[...baseFields,'lifeStatus','relatedExperience'].map(id=>({id,text:b[id]||'',...reuseProvenance(b,id),...(lifeBackgroundEntries(b).find(e=>e.field===id)?{actor:'real_user',timeScope:lifeBackgroundEntries(b).find(e=>e.field===id).timeScope}:{})})),...Object.entries(s.answers).filter(([id,a])=>ORDINARY_BY_ID[id]&&answerText(a)).map(([id,a])=>({id,text:answerText(a),question:questionTitle(QUESTION_BY_ID[id],s.questionMeta?.[id],b),timeScope:s.answerScopes?.[id]?.timeScope||questionTime(b),actor:'real_user'})),...activeReusedAnswers(b).map(a=>({id:a.id,text:[...a.selected,a.text].filter(Boolean).join('；'),question:a.question,actor:'real_user',timeScope:a.sourceTime,origin:{lifeId:a.lifeId,node:a.sourceNode,context:a.sourceContext,questionId:a.questionId,question:a.question},applicability:{confirmed:true,meaning:'已核对适用于本次，不改写原时间'}})),...(s.confirmations||[]).map((text,i)=>({id:'confirmation:'+i,text})),{id:'extra',text:s.extra||''}].filter(x=>x.text);}
export function supplementaryContext(b){const s=supplementState(b);return {behaviorReferences:scenarioReferences(s.scenario,supplementKey(b)),answers:Object.entries(s.answers).filter(([id,a])=>ORDINARY_BY_ID[id]&&answerText(a)).map(([id,a])=>({id,question:questionTitle(QUESTION_BY_ID[id],s.questionMeta?.[id],b),...questionMeaning(QUESTION_BY_ID[id],s.questionMeta?.[id]),purpose:KEY_QUESTION_BY_ID[id]?s.questionMeta?.[id]?.useInStory||QUESTION_BY_ID[id].purpose:questionMeaning(QUESTION_BY_ID[id],s.questionMeta?.[id]).purpose,answerContext:s.answerScopes?.[id]||null,timeScope:s.answerScopes?.[id]?.timeScope||questionTime(b),tense:s.answerScopes?.[id]?.timeScope?.tense||questionTime(b).tense,selected:a.selected||[],text:a.text||'',meaning:'仅按原话理解；手写纠正优先于被纠正的选项，不确定保持未知；若answerContext与当前故事已不相干，则保留原文但不应用到当前剧情'})).concat(activeReusedAnswers(b)),reusedFields:activeReuseEntries(b).filter(e=>e.kind==='field'),skipped:Object.keys(s.answers).filter(id=>s.answers[id].skipped),extra:s.extra||'',confirmations:s.confirmations||[],latestConfirmation:{question:b.followupQuestion||'',answer:b.followupSkipped?'':b.followupAnswer||'',skipped:Boolean(b.followupSkipped)},settingRecord:settingRecord(b,s,supplementSources(b),answerText,unknownAnswer),expectations:safeExpectations(s,b)};}
export function validateSupplement(b){
 for(const a of activeReusedAnswers(b)){const q=BANK_BY_ID[a.questionId];if(!q||!validSelections(q,a.selected))throw Error('supplement_input');}
 if(!b.supplementary)return;
 if(typeof b.supplementary!=='string'||b.supplementary.length>65000)throw Error('supplement_input');
 const e=JSON.parse(b.supplementary);if(!Array.isArray(e.contexts)||e.contexts.length>3)throw Error('supplement_input');
 for(const {key,basis,state:s} of e.contexts){if((basis!=null&&(typeof basis!=='string'||basis.length>32))||typeof key!=='string'||key.length>32||!s||!Array.isArray(s.shown)||s.shown.length>8||new Set(s.shown).size!==s.shown.length||s.shown.some(id=>!QUESTION_BY_ID[id])||!s.answers||typeof s.answers!=='object'||Object.keys(s.answers).some(id=>!s.shown.includes(id))||!Array.isArray(s.confirmations)||s.confirmations.length>2||s.confirmations.some(t=>typeof t!=='string'||t.length>500)||typeof s.extra!=='string'||s.extra.length>500)throw Error('supplement_input');
  for(const [id,a] of Object.entries(s.answers)){const q=QUESTION_BY_ID[id];if(SCENARIO_BY_ID[id]||!a||!validSelections(q,a.selected)||typeof a.text!=='string'||a.text.length>500||typeof a.skipped!=='boolean')throw Error('supplement_input');}
  if(s.confirmationContexts!=null&&(!Array.isArray(s.confirmationContexts)||s.confirmationContexts.length>2||s.confirmationContexts.some(c=>!Number.isInteger(c.sourceIndex)||c.sourceIndex<0||c.sourceIndex>=s.confirmations.length||typeof c.question!=='string'||c.question.length>400||!Array.isArray(c.gapKeys)||c.gapKeys.length>8||c.gapKeys.some(k=>! /^[a-z][a-z0-9_-]{0,47}$/.test(k)))))throw Error('supplement_input');
  if(s.plan?.generationUnknowns!=null&&(!Array.isArray(s.plan.generationUnknowns)||s.plan.generationUnknowns.length>8||s.plan.generationUnknowns.some(q=>!ORDINARY_BY_ID[q?.id]||['question','missingInformation','useInStory'].some(k=>typeof q[k]!=='string'||q[k].length>300))))throw Error('supplement_input');
  if(s.criticalUnknowns!=null&&(!Array.isArray(s.criticalUnknowns)||s.criticalUnknowns.length>8||s.criticalUnknowns.some(g=>!validCriticalGap(g))))throw Error('supplement_input');
  if(s.shown.some(id=>KEY_QUESTION_BY_ID[id]&&(!s.questionMeta?.[id]?.questionText||s.questionMeta[id].questionText.length>180)))throw Error('supplement_input');
  if(s.questionMeta&&Object.values(s.questionMeta).some(q=>q.questionText!=null&&(typeof q.questionText!=='string'||q.questionText.length>180)))throw Error('supplement_input');
  if(s.questionMeta&&Object.values(s.questionMeta).some(q=>q.displayedQuestionText!=null&&(typeof q.displayedQuestionText!=='string'||q.displayedQuestionText.length>400)))throw Error('supplement_input');
  if(s.scenario!=null){const q=s.scenario;if(!SCENARIO_BY_ID[q.id]||!s.shown.includes(q.id)||typeof q.answer!=='string'||q.answer.length>500||typeof q.skipped!=='boolean'||typeof q.scopeKey!=='string')throw Error('supplement_input');}
  if(s.recentScenarios!=null&&(!Array.isArray(s.recentScenarios)||s.recentScenarios.length>5||s.recentScenarios.some(x=>!SCENARIO_BY_ID[x.id])))throw Error('supplement_input');
  if(!Array.isArray(s.pages)||s.pages.length>8||s.pages.some(p=>!Array.isArray(p)||p.length>3||p.some(id=>!s.shown.includes(id)))||!Number.isInteger(s.page)||s.page<0||s.page>s.pages.length)throw Error('supplement_input');
  if(s.plan!=null&&(!Array.isArray(s.plan.questions)||s.plan.questions.length>3||s.plan.questions.some(q=>!q||!QUESTION_BY_ID[q.id])||(s.plan.conflict&&(!Array.isArray(s.plan.conflict.evidence)||typeof s.plan.conflict.question!=='string'||s.plan.conflict.evidence.some(e=>typeof e?.text!=='string')))))throw Error('supplement_input');
 }
}

function safeExpectations(s,b){if(!s.plan?.expectations)return null;const sources=new Map(supplementSources(b).map(x=>[x.id,x.text]));return {mustKeep:(s.plan.expectations.mustKeep||[]).filter(x=>sources.get(x.sourceId)?.includes(x.text)),respondTo:(s.plan.expectations.respondTo||[]).filter(x=>sources.get(x.sourceId)?.includes(x.text)),free:[],unknown:[]};}
