import React,{useEffect,useState} from 'react';
const n=v=>v==null?'未知':v;
const money=(a,b)=>a===b?'¥'+a.toFixed(8):'¥'+a.toFixed(8)+'～'+b.toFixed(8);
function Summary({title,data}){return <div><h3>{title}</h3><p>{data.requests} 次实际出站请求；用量不完整 {data.unknownUsage} 次。</p><p>已知输入 {data.knownInput}（未知 {data.unknownInput} 次）· 已知输出 {data.knownOutput}（未知 {data.unknownOutput} 次）· 已知总 Token {data.knownTotal}（未知 {data.unknownTotal} 次）</p><p>可估算部分费用：{money(data.estimatedMin,data.estimatedMax)}（估算）；另有 {data.unpriced} 次无法估算。</p></div>;}
export default function UsagePanel({busy}){
 const [open,setOpen]=useState(false),[data,setData]=useState(null),[error,setError]=useState('');
 async function refresh(){try{const r=await fetch('/api/usage');if(!r.ok)throw Error();setData(await r.json());setError('');}catch{setError('用量记录暂时无法读取，请稍后刷新。');}}
 useEffect(()=>{if(open && !busy)refresh();},[open,busy]);
 return <details className="usage-panel" onToggle={e=>setOpen(e.currentTarget.open)}><summary>用量明细</summary><p className="small">仅汇总本项目本机记录，不代表完整账户消耗。Token 来自供应商 usage；缓存包含在输入中，不重复相加。未返回用量不代表零消耗。</p><p>实际扣款与余额：未知，请到 <a href="https://platform.minimax.cn/user-center/payment/balance" target="_blank" rel="noreferrer">MiniMax 国内站控制台</a> 核对。未接入官方账单或余额接口。</p><button type="button" className="text-button" onClick={refresh}>刷新用量</button>{error && <p role="alert">{error}</p>}{data && <><Summary title="本机记录汇总" data={data.summary}/><Summary title="本轮开发测试汇总（独立标记）" data={data.development}/><p className="small">MiniMax-M2.5 国内站标准价格：输入2.1、输出8.4、缓存读取0.21元/百万Token；{data.pricing.checked}核对。缓存未知时费用显示区间；其他模型、站点或不明历史价格不估算。<a href={data.pricing.source} target="_blank" rel="noreferrer">官方价格</a>。损坏记录 {data.unreadable} 条未纳入。</p><div className="usage-table"><table><thead><tr>{['时间 / 请求编号','任务 / 模型','状态','输入','输出','总Token','其中缓存','费用（估算）'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.records.map(r=><tr key={r.requestId}><td>{r.time}<br/><small>{r.requestId}</small>{r.auditGroup===data.developmentGroup && <small> · 本轮开发测试</small>}</td><td>{r.task==='story'?'故事':'聊天'}<br/>{r.model}</td><td>{r.sent===false?'未出站 / ':''}{{success:'成功',failed:'失败',interrupted:'中断',unfinished:'未完成（状态未知）'}[r.status] || '未知'}{r.errorCategory && <small> · {r.errorCategory}</small>}</td><td>{n(r.inputTokens)}</td><td>{n(r.outputTokens)}</td><td>{n(r.totalTokens)}</td><td>{n(r.cachedTokens)}</td><td>{r.estimate?money(r.estimate.min,r.estimate.max):'未知'}</td></tr>)}</tbody></table></div></>}</details>;
}
